### ISSUE TITLE
repo should include a `project/build.properties` file specifying sbt version

### ISSUE THREAD

**Issue by SethTisue** [ermine-language/ermine-scala-core#1]
e.g.:

```
sbt.version=0.12.4
```

this is standard practice; iirc it's point 1 in Josh Suereth's "Effective SBT" talk.

(I'd submit it as a pull request, but I wouldn't be able to test it because I can't currently build because of missing dependencies; @joshcough says he's working on that)

**Comment by joshcough** [comment]
added. thanks.
